from console_logger import ConsoleLogger
from naive_task_runner import NaiveTaskRunner
from src.implementations.testing.parent_task import ParentTask
from stored_task_instantiator import StoredTaskInstantiator